SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[owid-covid-data 230113](
	[iso_code] [nvarchar](50) NULL,
	[continent] [nvarchar](50) NULL,
	[location] [nvarchar](50) NULL,
	[date] [nvarchar](50) NULL,
	[total_cases] [nvarchar](50) NULL,
	[new_cases] [nvarchar](50) NULL,
	[new_cases_smoothed] [nvarchar](50) NULL,
	[total_deaths] [nvarchar](50) NULL,
	[new_deaths] [nvarchar](50) NULL,
	[new_deaths_smoothed] [nvarchar](50) NULL,
	[total_cases_per_million] [nvarchar](50) NULL,
	[new_cases_per_million] [nvarchar](50) NULL,
	[new_cases_smoothed_per_million] [nvarchar](50) NULL,
	[total_deaths_per_million] [nvarchar](50) NULL,
	[new_deaths_per_million] [nvarchar](50) NULL,
	[new_deaths_smoothed_per_million] [nvarchar](50) NULL,
	[reproduction_rate] [nvarchar](50) NULL,
	[icu_patients] [nvarchar](50) NULL,
	[icu_patients_per_million] [nvarchar](50) NULL,
	[hosp_patients] [nvarchar](50) NULL,
	[hosp_patients_per_million] [nvarchar](50) NULL,
	[weekly_icu_admissions] [nvarchar](50) NULL,
	[weekly_icu_admissions_per_million] [nvarchar](50) NULL,
	[weekly_hosp_admissions] [nvarchar](50) NULL,
	[weekly_hosp_admissions_per_million] [nvarchar](50) NULL,
	[total_tests] [nvarchar](max) NULL,
	[new_tests] [nvarchar](50) NULL,
	[total_tests_per_thousand] [nvarchar](50) NULL,
	[new_tests_per_thousand] [nvarchar](50) NULL,
	[new_tests_smoothed] [nvarchar](50) NULL,
	[new_tests_smoothed_per_thousand] [nvarchar](50) NULL,
	[positive_rate] [nvarchar](50) NULL,
	[tests_per_case] [nvarchar](50) NULL,
	[tests_units] [nvarchar](50) NULL,
	[total_vaccinations] [nvarchar](50) NULL,
	[people_vaccinated] [nvarchar](50) NULL,
	[people_fully_vaccinated] [nvarchar](50) NULL,
	[total_boosters] [nvarchar](50) NULL,
	[new_vaccinations] [nvarchar](50) NULL,
	[new_vaccinations_smoothed] [nvarchar](50) NULL,
	[total_vaccinations_per_hundred] [nvarchar](50) NULL,
	[people_vaccinated_per_hundred] [nvarchar](50) NULL,
	[people_fully_vaccinated_per_hundred] [nvarchar](50) NULL,
	[total_boosters_per_hundred] [nvarchar](50) NULL,
	[new_vaccinations_smoothed_per_million] [nvarchar](50) NULL,
	[new_people_vaccinated_smoothed] [nvarchar](50) NULL,
	[new_people_vaccinated_smoothed_per_hundred] [nvarchar](50) NULL,
	[stringency_index] [nvarchar](50) NULL,
	[population_density] [nvarchar](50) NULL,
	[median_age] [nvarchar](50) NULL,
	[aged_65_older] [nvarchar](50) NULL,
	[aged_70_older] [nvarchar](50) NULL,
	[gdp_per_capita] [nvarchar](50) NULL,
	[extreme_poverty] [nvarchar](50) NULL,
	[cardiovasc_death_rate] [nvarchar](50) NULL,
	[diabetes_prevalence] [nvarchar](50) NULL,
	[female_smokers] [nvarchar](50) NULL,
	[male_smokers] [nvarchar](50) NULL,
	[handwashing_facilities] [nvarchar](50) NULL,
	[hospital_beds_per_thousand] [nvarchar](50) NULL,
	[life_expectancy] [nvarchar](50) NULL,
	[human_development_index] [nvarchar](50) NULL,
	[population] [nvarchar](50) NULL,
	[excess_mortality_cumulative_absolute] [nvarchar](50) NULL,
	[excess_mortality_cumulative] [nvarchar](50) NULL,
	[excess_mortality] [nvarchar](50) NULL,
	[excess_mortality_cumulative_per_million] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
