SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE FUNCTION [dbo].[fnGetTableDetails]()
RETURNS @t TABLE([schema] NVARCHAR(20), [rtn_nm] NVARCHAR(60))
AS
BEGIN
   DECLARE @sql NVARCHAR(4000)
   SET @SQL = CONCAT('INSERT INTO @t (COLUMN_NAME, DATA_TYPE, CHAR_LEN, IS_NULLABLE, ORDINAL) SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, ORDINAL_POSITION FROM ut.INFORMATION_SCHEMA. COLUMNS WHERE TABLE_NAME = ', 'AppLog')
   EXEC sp_executesql @SQL, N'@SQL, @t TABLE([schema] NVARCHAR(20), [rtn_nm] NVARCHAR(60)) OUTPUT',
   @t = @t OUTPUT;
RETURN

END





GO
