SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AttendanceStagingCourseHdr](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[course_nm] [varchar](400) NOT NULL,
	[section_nm] [varchar](20) NOT NULL,
	[stage] [varchar](7000) NULL,
 CONSTRAINT [PK_AttendanceStagingCourseHdr] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
