SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[Team](
	[team_id] [int] NOT NULL,
	[team_nm] [varchar](40) NULL,
	[github_project] [varchar](250) NULL,
	[team_gc] [varchar](100) NULL,
	[team_url] [varchar](300) NULL,
	[section_id] [int] NULL,
	[event_id] [int] NULL,
	[notes] [varchar](150) NULL,
 CONSTRAINT [PK_Team] PRIMARY KEY CLUSTERED 
(
	[team_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [IX_Team] ON [dbo].[Team]
(
	[team_nm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

ALTER TABLE [dbo].[Team]  WITH CHECK ADD  CONSTRAINT [FK_Team_Event] FOREIGN KEY([event_id])
REFERENCES [dbo].[Event] ([event_id])

ALTER TABLE [dbo].[Team] CHECK CONSTRAINT [FK_Team_Event]

GO
