SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AttendanceStagingHdr](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[stu_id] [varchar](2000) NULL,
	[nm] [varchar](2000) NULL,
	[attendance] [varchar](2000) NULL,
	[hdr] [varchar](max) NOT NULL,
 CONSTRAINT [PK_AttendanceStagingHdr] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
