SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [test].[TSU1_031_table](
	[test_num] [nvarchar](4) NOT NULL,
	[inp] [nvarchar](100) NULL,
	[exp] [int] NULL,
 CONSTRAINT [PK_TSU1_031_table] PRIMARY KEY CLUSTERED 
(
	[test_num] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

