CREATE TABLE [dbo].[Agency] (
    [agency_id]                INT            IDENTITY (1, 1) NOT NULL,
    [agency_nm]                VARCHAR (250)  NOT NULL,
    [agencyType_id]            INT            NULL,
    [area_id]                  INT            NULL,
    [delegate_id]              INT            NULL,
    [status_id]                INT            NULL,
    [first_reg]                DATE           NULL,
    [notes]                    VARCHAR (250)  NULL,
    [quality]                  INT            NULL,
    [primary_contact_id]       INT            NULL,
    [preferred_contact_method] VARCHAR (50)   NULL,
    [role]                     VARCHAR (50)   NULL,
    [phone]                    VARCHAR (250)  NULL,
    [email]                    VARCHAR (255)  NULL,
    [whatsApp]                 VARCHAR (50)   NULL,
    [viber]                    VARCHAR (50)   NULL,
    [facebook]                 VARCHAR (100)  NULL,
    [messenger]                VARCHAR (100)  NULL,
    [website]                  VARCHAR (255)  NULL,
    [address]                  VARCHAR (250)  NULL,
    [notes_2]                  VARCHAR (250)  NULL,
    [old_notes]                VARCHAR (250)  NULL,
    [age]                      INT            NULL,
    [actions_08_OCT]           VARCHAR (100)  NULL,
    [jan_16_2025]              VARCHAR (100)  NULL,
    [action_by_dt]             DATE           NULL,
    [replied]                  BIT            NULL,
    [history]                  VARCHAR (1000) NULL,
    CONSTRAINT [PK_Agency] PRIMARY KEY CLUSTERED ([agency_id] ASC),
    CONSTRAINT [UQ_Agency_nm] UNIQUE NONCLUSTERED ([agency_nm] ASC)
);

