CREATE TABLE [dbo].[AgencyStaging] (
    [agency_nm]                VARCHAR (250) NOT NULL,
    [agency_type]              VARCHAR (50)  NULL,
    [area]                     VARCHAR (50)  NULL,
    [delegate_nm]              VARCHAR (10)  NULL,
    [status]                   VARCHAR (50)  NULL,
    [first_reg]                VARCHAR (50)  NULL,
    [notes]                    VARCHAR (255) NULL,
    [quality]                  VARCHAR (50)  NULL,
    [primary_contact_nm]       VARCHAR (250) NULL,
    [preferred_contact_method] VARCHAR (50)  NULL,
    [role]                     VARCHAR (50)  NULL,
    [phone]                    VARCHAR (250) NULL,
    [email]                    VARCHAR (255) NULL,
    [whatsApp]                 VARCHAR (50)  NULL,
    [viber]                    VARCHAR (50)  NULL,
    [facebook]                 VARCHAR (100) NULL,
    [messenger]                VARCHAR (100) NULL,
    [website]                  VARCHAR (255) NULL,
    [address]                  VARCHAR (250) NULL,
    [notes_2]                  VARCHAR (250) NULL,
    [old_notes]                VARCHAR (250) NULL,
    [age]                      INT           NULL,
    [actions_08_OCT]           VARCHAR (100) NULL,
    [jan_16_2025]              VARCHAR (100) NULL,
    [action_by_dt]             VARCHAR (100) NULL,
    [replied]                  VARCHAR (100) NULL,
    [history]                  VARCHAR (100) NULL,
    CONSTRAINT [PK_AgencyStaging] PRIMARY KEY CLUSTERED ([agency_nm] ASC)
);

