CREATE TABLE [dbo].[PropertySales] (
    [agency_id]                INT            NULL,
    [agencyType_id]            INT            NULL,
    [area_id]                  INT            NULL,
    [delegate_id]              VARCHAR (1)    NULL,
    [status_id]                VARCHAR (40)   NULL,
    [first_reg]                VARCHAR (8000) NULL,
    [notes]                    VARCHAR (509)  NULL,
    [quality]                  VARCHAR (25)   NULL,
    [contact_nm]               VARCHAR (286)  NULL,
    [phone]                    VARCHAR (8000) NULL,
    [preferred_contact_method] VARCHAR (500)  NULL,
    [email]                    VARCHAR (216)  NULL,
    [whatsapp]                 VARCHAR (45)   NULL,
    [viber]                    VARCHAR (14)   NULL,
    [facebook]                 VARCHAR (92)   NULL,
    [messenger]                VARCHAR (85)   NULL,
    [website]                  VARCHAR (319)  NULL,
    [address]                  VARCHAR (62)   NULL,
    [notes_2]                  VARCHAR (82)   NULL,
    [old_notes]                VARCHAR (155)  NULL,
    [date_1]                   VARCHAR (11)   NULL,
    [actions_08_oct]           VARCHAR (51)   NULL,
    [jan_16_2025]              VARCHAR (43)   NULL,
    [action_by_dt]             VARCHAR (7)    NULL,
    [replied]                  VARCHAR (25)   NULL,
    [history]                  VARCHAR (66)   NULL
);

