CREATE TABLE [dbo].[XL_sheets] (
    [TABLE_QUALIFIER] NVARCHAR (255) NULL,
    [TABLE_OWNER]     NVARCHAR (255) NULL,
    [TABLE_NAME]      NVARCHAR (255) NULL,
    [TABLE_TYPE]      NVARCHAR (255) NULL,
    [REMARKS]         NVARCHAR (255) NULL
);

